name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish for ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            asset_name: updater-linux-amd64
          - os: ubuntu-24.04-arm
            asset_name: updater-linux-arm64
    runs-on: ${{matrix.os}}
    steps:
      - uses: laytan/setup-odin@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v5

      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on V$(date +%Y.%m.%d)" >> $GITHUB_ENV
          echo "TAG_NAME=V$(date +%Y.%m.%d)" >> $GITHUB_ENV

      - name: Build updater
        run: |
          pushd miniz/src
          make
          popd
          pushd tinyfiledialogs
          ./build.sh
          popd
          odin build updater.odin -file -o:speed

      - name: Release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUBTOKEN }}
          tag: ${{ env.TAG_NAME }}
          file: updater
          asset_name: ${{ matrix.asset_name }}
